export const OBJs = [
    {
        id: 1,
        url: "./OBJ/SR-withoutGlass.glb",
        name: "showroom",
        positionX: 0,
        positionY: -0.1,
        positionZ: 0.5,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotationX: 0,
        rotationY: 0,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 2,
        url: "./OBJ/HumanDos.glb",
        name: "HumanDos",
        positionX: -7.849000625806955,
        positionY: 0,
        positionZ: -13.538887828143084,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotationX: 0,
        rotationY: 75,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 3,
        url: "./OBJ/HumanHanche.glb",
        name: "HumanHanche",
        positionX: 9,
        positionY: 0,
        positionZ: 37,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotationX: 0,
        rotationY: 0,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 4,
        url: "./OBJ/SignatureFil.glb",
        name: "SignatureFil",
        positionX: -8,
        positionY: 10,
        positionZ: 45.5,
        scaleX: 90,
        scaleY: 90,
        scaleZ: 90,
        rotationX: 90,
        rotationY: 0,
        rotationZ: 230,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xAEAEAE,
    },
    {
        id: 5,
        url: "./OBJ/plantearbre2.glb",
        name: "PlanteArbre",
        positionX: -16,
        positionY: 0,
        positionZ: -0.4,
        scaleX: 0.45,
        scaleY: 0.45,
        scaleZ: 0.45,
        rotationX: 0,
        rotationY: 230,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 6,
        url: "./OBJ/plante.glb",
        name: "Plante",
        positionX: -19,
        positionY: 0,
        positionZ: -17,
        scaleX: 0.9,
        scaleY: 0.9,
        scaleZ: 0.9,
        rotationX: 0,
        rotationY: 90,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 7,
        url: "./OBJ/plantearbre2.glb",
        name: "PlanteArbre2",
        positionX: -16,
        positionY: 0,
        positionZ: -33,
        scaleX: 0.45,
        scaleY: 0.45,
        scaleZ: 0.45,
        rotationX: 0,
        rotationY: 90,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 8,
        url: "./OBJ/plante.glb",
        name: "Plante2",
        positionX: -19,
        positionY: 0,
        positionZ: 16,
        scaleX: 0.9,
        scaleY: 0.9,
        scaleZ: 0.9,
        rotationX: 0,
        rotationY: 90,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 9,
        url: "./OBJ/plantearbre2.glb",
        name: "Plantearbre3",
        positionX: -16,
        positionY: 0,
        positionZ: 32,
        scaleX: 0.45,
        scaleY: 0.45,
        scaleZ: 0.45,
        rotationX: 0,
        rotationY: 120,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xFFFFFF,
    },
    {
        id: 10,
        url: "./OBJ/signatureNathalie.glb",
        name: "Signature",
        positionX: 2.8,
        positionY: 3.4,
        positionZ: -34.5,
        scaleX: 27,
        scaleY: 27,
        scaleZ: 27,
        rotationX: 90,
        rotationY: 0,
        rotationZ: 270,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xDCDCDC,
    },
    {
        id: 11,
        url: "./OBJ/projecteur.glb",
        name: "Projecteur",
        positionX: 11,
        positionY: 14.3,
        positionZ: 32.5,
        scaleX: 0.2,
        scaleY: 0.2,
        scaleZ: 0.2,
        rotationX: 0,
        rotationY: 180,
        rotationZ: 0,
        castShadow: true,
        receiveShadow: true,
        colorMesh: 0xDCDCDC,
    },

];
